{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x7ff415ca51c0>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "LTE\n",
      "LTE\n",
      "WCDMA\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import geopandas as gpd\n",
    "from shapely.wkt import loads\n",
    "\n",
    "import numpy as np\n",
    "import plotly.express as px  # (version 4.7.0 or higher)\n",
    "import plotly.graph_objects as go\n",
    "from dash import Dash, dcc, html, Input, Output  # pip install dash (version 2.0.0 or higher)\n",
    "import mercantile\n",
    "import json\n",
    "import warnings\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "\n",
    "app = Dash(__name__)\n",
    "\n",
    "#server = app.server\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# Leer parquet procesado\n",
    "pivot_table = pd.read_parquet(\"processed_data.parquet\")\n",
    "\n",
    "# Convertir geometría WKT a objeto geométrico\n",
    "pivot_table['geometry'] = pivot_table['geometry'].apply(loads)\n",
    "\n",
    "# Crear GeoDataFrame\n",
    "gdf_csv = gpd.GeoDataFrame(pivot_table, geometry=\"geometry\")\n",
    "\n",
    "if gdf_csv.crs is None:\n",
    "    gdf_csv.set_crs(epsg=4326, inplace=True)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# App layout\n",
    "app.layout = html.Div([\n",
    "\n",
    "    html.H1(\"Comparación Cobertura Móvil Tigo y Claro - Guatemala. Periodo: Octubre 2024 a Marzo 2025\", style={'text-align': 'center'}),\n",
    "\n",
    "    dcc.Dropdown(\n",
    "        id=\"slct_tech\",\n",
    "        options=[\n",
    "            {\"label\": \"5G\", \"value\": 'NR'},\n",
    "            {\"label\": \"4G\", \"value\": 'LTE'},\n",
    "            {\"label\": \"WCDMA\", \"value\": 'WCDMA'},\n",
    "            {\"label\": \"CDMA\", \"value\": 'CDMA'},\n",
    "            {\"label\": \"GSM\", \"value\": 'GSM'}\n",
    "        ],\n",
    "        multi=False,\n",
    "        value='LTE',\n",
    "        style={'width': \"40%\"}\n",
    "    ),\n",
    "\n",
    "    html.Div(id='output_container', children=[]),\n",
    "    html.Br(),\n",
    "\n",
    "    dcc.Graph(id='my_tech_map', figure={})\n",
    "\n",
    "])\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "# Connect the Plotly graphs with Dash Components\n",
    "warnings.filterwarnings(\"ignore\", category=FutureWarning)\n",
    "\n",
    "@app.callback(\n",
    "    [Output(component_id='output_container', component_property='children'),\n",
    "     Output(component_id='my_tech_map', component_property='figure')],\n",
    "#     Output(component_id='bar_plot', component_property='figure')],\n",
    "    [Input(component_id='slct_tech', component_property='value')]\n",
    "    )\n",
    "\n",
    "def update_graph(option_slctd):\n",
    "    print(option_slctd)\n",
    "\n",
    "    container = f\"The selected technology was: {option_slctd}\"\n",
    "\n",
    "    # Filtrar GeoDataFrame por tecnología\n",
    "    dff = gdf_csv[gdf_csv[\"technology\"] == option_slctd]\n",
    "\n",
    "    if dff.empty:\n",
    "        print(\"GeoDataFrame is empty.\")\n",
    "        return container, go.Figure()\n",
    "\n",
    "    # Convertir GeoDataFrame a GeoJSON\n",
    "    geojson = json.loads(dff.to_json())\n",
    "\n",
    "    # Reproyectar temporalmente para calcular centroides correctos\n",
    "    gdf_projected = dff.to_crs(epsg=3857)\n",
    "    centroid = gdf_projected.geometry.centroid.to_crs(epsg=4326)\n",
    "\n",
    "    # Crear figura\n",
    "    fig = px.choropleth_mapbox(\n",
    "        dff,\n",
    "        geojson=geojson,\n",
    "        locations=dff.index,\n",
    "        color=\"comparison\",  # Cambia a otra columna si prefieres\n",
    "        mapbox_style=\"carto-positron\",\n",
    "        center={\n",
    "            \"lat\": centroid.y.mean(),\n",
    "            \"lon\": centroid.x.mean()\n",
    "        },\n",
    "        zoom=11,  # Ajusta según nivel de detalle de tus tiles\n",
    "        opacity=0.6,\n",
    "        hover_name=\"quadkey\"\n",
    "    )\n",
    "\n",
    "    fig.update_layout(\n",
    "        width=1700,\n",
    "        height=900,\n",
    "        margin={\"r\": 0, \"t\": 0, \"l\": 0, \"b\": 0},\n",
    "    )\n",
    "\n",
    "    return container, fig\n",
    "\n",
    "# ------------------------------------------------------------------------------\n",
    "if __name__ == '__main__':\n",
    "    app.run_server(debug=True)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
